#数据库相关配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huige?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
  banner:
    location: classpath:banner.webp
#    mybatis的mapper 位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9000